import PackagePluginModule from '../PackagePluginModule';
import ButtonIcon from "../../icons/audio-lines.svg?raw";
import { PreactButtonPlugin, type PreactButtonPluginConfig } from '../PreactButtonPlugin/PreactButtonPlugin';
import type { ComponentChildren } from 'preact';
import type { RealTimeCaptions } from './RealTimeCaptions';

import { MainAppContent } from './ui/MainAppContent';




export default class RealTimeCaptionsPlugin extends PreactButtonPlugin<PreactButtonPluginConfig> {

    _rtcTranscriber: RealTimeCaptions | null = null;

    getPluginModuleInstance() {
        return PackagePluginModule.Get();
    }

    get name() {
        return super.name || "es.upv.paella.ai.realTimeCaptions";
    }


    getAriaLabel() {
        return this.player.translate('AI Real-Time Captions');
    }

    getDescription() {
        return this.getAriaLabel();
    }

    async load() {
        this.icon = this.player.getCustomPluginIcon(this.name, "button") || ButtonIcon;
        
        const {VoxtralRealTimeCaptions} = await import('./VoxtralRealTimeCaptions');
        this._rtcTranscriber = new VoxtralRealTimeCaptions();        
    }

    // async getHelp() {
    //     return {
    //         title: "Discover AI-Generated Content",
    //         description: "Use this button to access helpful content generated by artificial intelligence like summaries, key questions, and audio insights. It’s designed to save you time and help you understand faster."
    //     };
    // }

    async isEnabled(): Promise<boolean> {
        if (!(await super.isEnabled())) {
            return false;
        }

        return true;
    }

    getReactNode(): ComponentChildren {
        return (<MainAppContent />);
    }


    // TRANSCRIBING METHODS
    

    getMainAudioPlayerElement(): HTMLVideoElement | null {
        const mainAudioPlayer = this.player.videoContainer?.streamProvider.mainAudioPlayer;

        const element = (mainAudioPlayer as any)?.video || null;

        if (element instanceof HTMLVideoElement) {
            return element;
        }

        return null;
    }

}


